
version: '3'

services:

  mysql-landlord:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: rootuser
      MYSQL_DATABASE: landlord
    ports:
      - "3308:3306"
    volumes:
      - $HOME/Workspace/Blue Algorithm/alphasim_demo.sql:/demo.sql